name: pansy_arch_flutter

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  pansy_arch:
    git:
      url: https://github.com/mocki-toki/pansy_architecture.git
      path: packages/pansy_arch
  flutter:
    sdk: flutter
  dino_flutter: ^1.0.0-pre.0

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4
