name: pansy_arch_go_router

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  pansy_arch_flutter:
    git:
      url: https://github.com/mocki-toki/pansy_architecture.git
      path: packages/pansy_arch_flutter
  go_router: ^6.0.0
